spring.application.name=aspose-demo
server.port=1990
aspose.should-use-license=${ASPOSE_SHOULD_USE_LICENSE:true}
aspose.public-key=${ASPOSE_PUBLIC_KEY:invalid}
aspose.private-key=${ASPOSE_PRIVATE_KEY:invalid}